sonar.projectKey=avishj_AutoCustomizeResume
sonar.organization=avishj
sonar.projectName=AutoCustomizeResume

sonar.python.version=3.13

sonar.sources=autocustomizeresume/
sonar.tests=tests/
sonar.test.exclusions=tests/**

sonar.python.coverage.reportPaths=coverage-unit.xml,coverage-integration.xml,coverage-e2e.xml
sonar.python.xunit.reportPath=results-*.xml

sonar.qualitygate.wait=true
sonar.qualitygate.timeout=300

sonar.sourceEncoding=UTF-8
